[author]
name = "Francis Billones"

[meta]
title = "Neural nets are non-linear linear transformations"
date = 2022-06-22T12:00:00+08:00
thumbnail = "https://blog.francisdb.net/assets/logo.svg"
url_title = "nnets-nonlinear-transformations"
description = "Neural networks are closer to matrices than actual brains."